apiVersion: apps/v1
kind: Deployment
metadata:
  name: [your-name]-app-deployment
  namespace: masterclass
  labels:
    app: [your-name]-app
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: [your-name]-app
  template:
    metadata:
      labels:
        app: [your-name]-app
    spec:
      containers:
        - name: [your-name]-app
          image: [your-image]
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "50m"
