apiVersion: apps/v1
kind: Deployment
metadata:
  name: [your-name]-app-deployment
  namespace: masterclass
  labels:
    app: [your-name]-app
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: [your-name]-app
  template:
    metadata:
      labels:
        app: [your-name]-app
    spec:
      containers:
        - name: [your-name]-app
          image: riyanatshittu/my-k8s-masterclass-springboot-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: / # replace with /actuator/health once you connect to db
              port: 8080
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: / # replace with /actuator/health once you connect to db
              port: 8080
            initialDelaySeconds: 60
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "250m"