apiVersion: v1
kind: Service
metadata:
  namespace: masterclass
  name:  [your-name]-app-service
spec:
  selector:
    app: [your-name]-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
